project_name: LaST_ssh
working_path: working_path
version_name: LaST_ssh_eval

seed: 42

model: LaST

data: SeaWaveCora
data_root: data
data_back:
- 7
- 1
- 40
- 40
data_pred:
- 7
- 1
- 40
- 40
data_mean:
- 0.8862621808307641
data_std:
- 0.04662053225539691
heat_cmap: Blues
draw_style: heat
draw_per_channel: true
inverse_transform: false

metrics:
- mae
- mse
- mae_pixel
- mse_pixel

epoch: 200
batch_size: 16
val_batch_size: 16
accumulate_grad_batches: 1
lr_scheduler: cosine
lr: 0.0005

d_model: 128
s_patch: 4
r_forward: 4
n_heads: 8
n_layer: 6
dropout: 0.1
drop_path: 0.1

attn_bias: false
s_kernel: 1
s_local:
- 3
- 3
- 3

fp16: true
device: gpu
ddp: false
n_device: 1
num_nodes: 1
num_workers: 0
gard_clip: 0.1
logger_wandb: false
n_model_save: 3
n_val_every: 1
