project_name: LaST_r
working_path: working_path
version_name: LaST_r_eval

seed: 42

model: LaST

data: r
data_root: data
data_back:
- 12
- 1
- 32
- 64
data_pred:
- 12
- 1
- 32
- 64
data_mean:
- 78.09089
data_std:
- 18.23997
heat_cmap: GnBu
draw_style: heat
draw_per_channel: true
inverse_transform: true

metrics:
- mae
- mse
- mae_pixel
- mse_pixel

epoch: 50
batch_size: 16
val_batch_size: 16
lr_scheduler: cosine
lr: 0.001

d_model: 128
s_patch: 4
r_forward: 4
n_heads: 8
n_layer: 12
dropout: 0.1
drop_path: 0.5

attn_bias: false
s_kernel: 1
s_local:
- 3
- 3
- 3

fp16: true
device: gpu
ddp: false
n_device: 1
num_nodes: 1
num_workers: 0
gard_clip: 0.1
logger_wandb: false
n_model_save: 3
n_val_every: 1
